pub mod Errors {
    pub const NOT_ENOUGH_FUNDS: felt252 = 'NOT_ENOUGH_FUNDS';
    pub const ALREADY_REGISTERED: felt252 = 'ALREADY_REGISTERED';
    pub const NAME_CANNOT_BE_EMPTY: felt252 = 'NAME_CANNOT_BE_EMPTY';
    pub const NAME_ALREADY_REGISTERED: felt252 = 'NAME_ALREADY_REGISTERED';
    pub const INVALID_FARM_INDEX: felt252 = 'INVALID_FARM_INDEX';
    pub const YOU_ARE_NOT_REGISTERED: felt252 = 'YOU_ARE_NOT_REGISTERED';
    pub const FARM_DOES_NOT_BELONG_TO_YOU: felt252 = 'FARM_DOES_NOT_BELONG_TO_YOU';
    pub const FARM_NOT_FOUND: felt252 = 'FARM_NOT_FOUND';
    pub const INVALID_PRODUCT_INDEX: felt252 = 'INVALID_PRODUCT_INDEX';
    pub const PRODUCT_DOES_NOT_EXIST: felt252 = 'PRODUCT_DOES_NOT_EXIST';
    pub const ONLY_BUYERS_CAN_REVIEW: felt252 = 'ONLY_BUYERS_CAN_REVIEW';
    pub const TRANSFER_FAILED: felt252 = 'TRANSFER_FAILED';
    pub const NOT_PURCHASED: felt252 = 'NOT_PURCHASED';
    pub const INSUFFICIENT_ALLOWANCE: felt252 = 'INSUFFICIENT_ALLOWANCE';
    pub const NOT_PRODUCT_OWNER: felt252 = 'NOT_PRODUCT_OWNER';
    pub const PRODUCT_NOT_IN_CART: felt252 = 'PRODUCT_NOT_IN_CART';
    pub const INVALID_QUANTITY: felt252 = 'INVALID_QUANTITY';
    pub const EMPTY_CART: felt252 = 'EMPTY_CART';
    pub const INVALID_PAYMENT: felt252 = 'INVALID_PAYMENT';
    pub const NO_PENDING_PAYMENT: felt252 = 'NO_PENDING_PAYMENT';
    pub const PAYMENT_NOT_CONFIRMED: felt252 = 'PAYMENT_NOT_CONFIRMED';
    pub const EMAIL_CANNOT_BE_EMPTY: felt252 = 'EMAIL_CANNOT_BE_EMPTY';
    pub const LOCATION_CANNOT_BE_EMPTY: felt252 = 'LOCATION_CANNOT_BE_EMPTY';
    pub const EMAIL_ALREADY_REGISTERED: felt252 = 'EMAIL_ALREADY_REGISTERED';
    pub const CONTACT_ALREADY_REGISTERED: felt252 = 'CONTACT_ALREADY_REGISTERED';
    pub const ADDRESS_ALREADY_REGISTERED: felt252 = 'ADDRESS_ALREADY_REGISTERED';
}

